#!/usr/bin/env python
"""
sentiment_plots_reddit.py

Read the sentiment CSV generated by sentiment_classify_reddit_comments.py and produce:
1) Bar chart and pie chart showing percentage of positive/neutral/negative comments (with total count note).
2) Grouped bar chart showing total upvotes vs downvotes per sentiment (positive/negative only).
3) Combined figure with all three plots side by side.
4) Year trend plot (positive vs negative by year, percentages) derived from comment age (e.g., 5y -> 2021).

Usage (with defaults so you can double-click):
  python sentiment_plots_reddit.py --input solid_perfumes_thread.sentiment.csv --outdir plots

Outputs:
  plots/sentiment_percentages_bar.png
  plots/sentiment_percentages_pie.png
  plots/upvotes_downvotes_by_sentiment.png
  plots/sentiment_combined.png
  plots/sentiment_trend_by_year.png

Requirements: pandas, matplotlib, seaborn
"""
import argparse
from pathlib import Path
import sys
import re
from datetime import datetime

import matplotlib
matplotlib.use("Agg")  # headless
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


DEFAULT_INPUT = "solid_perfumes_thread.sentiment.csv"
DEFAULT_OUTDIR = "plots"
SENTIMENT_ORDER = ["positive", "neutral", "negative"]
CURRENT_YEAR = 2026

AGE_RE = re.compile(r"(?P<num>\d+)\s*(?P<unit>y|yr|yrs|mo|d|h|m)", re.IGNORECASE)


def estimate_year_from_age(age: str):
    """Convert relative age (e.g., '5y') to approximate year."""
    if not isinstance(age, str):
        return None
    m = AGE_RE.search(age.strip())
    if not m:
        return None
    num = int(m.group("num"))
    unit = m.group("unit").lower()
    if unit in {"y", "yr", "yrs"}:
        return CURRENT_YEAR - num
    return CURRENT_YEAR


def load_df(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    df["sentiment"] = df["sentiment"].str.lower().str.strip()
    df["upvotes"] = pd.to_numeric(df.get("upvotes"), errors="coerce")
    df["downvotes"] = pd.to_numeric(df.get("downvotes"), errors="coerce")
    df["age"] = df.get("age")
    df["year_est"] = df["age"].apply(estimate_year_from_age)
    return df


def plot_percentages(df: pd.DataFrame, outdir: Path):
    df_core = df[df["sentiment"].isin(SENTIMENT_ORDER)].copy()
    counts = df_core["sentiment"].value_counts()
    total = counts.sum()
    pct = (counts / total * 100).reindex(SENTIMENT_ORDER).fillna(0)
    total_label = f"Total comments: {int(total)}"

    sns.set_theme(style="whitegrid")

    # Bar chart
    plt.figure(figsize=(6, 4))
    ax = sns.barplot(x=pct.index, y=pct.values, palette=["#4caf50", "#9e9e9e", "#f44336"])
    plt.ylabel("Percentage (%)")
    plt.xlabel("Sentiment")
    plt.title("Comment Sentiment Distribution")
    for i, v in enumerate(pct.values):
        plt.text(i, v + 0.5, f"{v:.1f}%", ha="center", va="bottom", fontsize=9)
    ax.text(0.98, 0.95, total_label, ha="right", va="top", transform=ax.transAxes, fontsize=9, color="#555555")
    plt.tight_layout()
    outdir.mkdir(parents=True, exist_ok=True)
    plt.savefig(outdir / "sentiment_percentages_bar.png", dpi=150)
    plt.close()

    # Pie chart
    plt.figure(figsize=(5, 5))
    colors = ["#4caf50", "#9e9e9e", "#f44336"]
    plt.pie(pct.values, labels=pct.index, autopct="%1.1f%%", startangle=140, colors=colors)
    plt.title("Comment Sentiment Share")
    plt.text(0.98, 0.95, total_label, ha="right", va="top", transform=plt.gca().transAxes, fontsize=9, color="#555555")
    plt.tight_layout()
    plt.savefig(outdir / "sentiment_percentages_pie.png", dpi=150)
    plt.close()


def plot_votes_by_sentiment(df: pd.DataFrame, outdir: Path):
    df_votes = df[df["sentiment"].isin(["positive", "negative"])].copy()
    agg = (
        df_votes.groupby("sentiment")[["upvotes", "downvotes"]]
        .sum(min_count=1)
        .reindex(["positive", "negative"])
        .fillna(0)
    )
    agg = agg.reset_index().melt(
        id_vars="sentiment",
        value_vars=["upvotes", "downvotes"],
        var_name="vote_type",
        value_name="count",
    )

    sns.set_theme(style="whitegrid")
    plt.figure(figsize=(7, 4))
    sns.barplot(
        data=agg,
        x="sentiment",
        y="count",
        hue="vote_type",
        palette={"upvotes": "#2196f3", "downvotes": "#ff9800"},
    )
    plt.ylabel("Total votes")
    plt.xlabel("Sentiment of comment")
    plt.title("Votes by Comment Sentiment")
    plt.tight_layout()
    outdir.mkdir(parents=True, exist_ok=True)
    plt.savefig(outdir / "upvotes_downvotes_by_sentiment.png", dpi=150)
    plt.close()


def plot_combined(df: pd.DataFrame, outdir: Path):
    df_core = df[df["sentiment"].isin(SENTIMENT_ORDER)].copy()
    counts = df_core["sentiment"].value_counts().reindex(SENTIMENT_ORDER).fillna(0)
    total = counts.sum()
    pct = (counts / total * 100).fillna(0) if total > 0 else counts
    total_label = f"Total comments: {int(total)}"

    df_votes = df[df["sentiment"].isin(["positive", "negative"])].copy()
    agg_votes = (
        df_votes.groupby("sentiment")[["upvotes", "downvotes"]]
        .sum(min_count=1)
        .reindex(["positive", "negative"])
        .fillna(0)
    )
    agg_votes = agg_votes.reset_index().melt(
        id_vars="sentiment",
        value_vars=["upvotes", "downvotes"],
        var_name="vote_type",
        value_name="count",
    )

    sns.set_theme(style="whitegrid")
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))

    sns.barplot(ax=axes[0], x=pct.index, y=pct.values, palette=["#4caf50", "#9e9e9e", "#f44336"])
    axes[0].set_ylabel("Percentage (%)")
    axes[0].set_xlabel("Sentiment")
    axes[0].set_title("Sentiment Distribution")
    for i, v in enumerate(pct.values):
        axes[0].text(i, v + 0.5, f"{v:.1f}%", ha="center", va="bottom", fontsize=9)
    axes[0].text(0.98, 0.95, total_label, ha="right", va="top", transform=axes[0].transAxes, fontsize=9, color="#555555")

    colors = ["#4caf50", "#9e9e9e", "#f44336"]
    axes[1].pie(pct.values, labels=pct.index, autopct="%1.1f%%", startangle=140, colors=colors)
    axes[1].set_title("Sentiment Share")
    axes[1].text(0.98, 0.95, total_label, ha="right", va="top", transform=axes[1].transAxes, fontsize=9, color="#555555")

    sns.barplot(
        ax=axes[2],
        data=agg_votes,
        x="sentiment",
        y="count",
        hue="vote_type",
        palette={"upvotes": "#2196f3", "downvotes": "#ff9800"},
    )
    axes[2].set_ylabel("Total votes")
    axes[2].set_xlabel("Sentiment of comment")
    axes[2].set_title("Votes by Sentiment")
    axes[2].legend(title="Vote type")

    plt.tight_layout()
    outdir.mkdir(parents=True, exist_ok=True)
    plt.savefig(outdir / "sentiment_combined.png", dpi=150)
    plt.close()


def plot_trend_by_year(df: pd.DataFrame, outdir: Path):
    df_year = df[df["sentiment"].isin(["positive", "negative"])].copy()
    df_year = df_year.dropna(subset=["year_est"])
    outdir.mkdir(parents=True, exist_ok=True)

    if df_year.empty:
        plt.figure(figsize=(6, 3))
        plt.text(
            0.5,
            0.5,
            "No year info available in data.\nAdd 'age' values to comments to plot trend.",
            ha="center",
            va="center",
            fontsize=10,
            wrap=True,
        )
        plt.axis("off")
        plt.tight_layout()
        plt.savefig(outdir / "sentiment_trend_by_year.png", dpi=150)
        plt.close()
        return

    agg_counts = (
        df_year.groupby(["year_est", "sentiment"])
        .size()
        .reset_index(name="count")
        .sort_values("year_est")
    )
    total_per_year = agg_counts.groupby("year_est")["count"].transform("sum")
    agg_counts["pct"] = agg_counts["count"] / total_per_year * 100
    total_label = f"Total comments: {len(df_year)}"

    plt.figure(figsize=(8, 4))
    ax = sns.barplot(
        data=agg_counts,
        x="year_est",
        y="pct",
        hue="sentiment",
        palette={"positive": "#4caf50", "negative": "#f44336"},
    )
    plt.xlabel("Year (approx.)")
    plt.ylabel("Percentage of comments (%)")
    plt.title("Sentiment trend by year")
    for p in ax.patches:
        height = p.get_height()
        if height > 0:
            ax.text(p.get_x() + p.get_width() / 2, height + 0.5, f"{height:.1f}%", ha="center", va="bottom", fontsize=8)
    ax.text(0.98, 0.95, total_label, ha="right", va="top", transform=ax.transAxes, fontsize=9, color="#555555")
    plt.tight_layout()
    plt.savefig(outdir / "sentiment_trend_by_year.png", dpi=150)
    plt.close()


def main():
    # Allow running without CLI args (e.g., double-click)
    if len(sys.argv) == 1:
        in_path = Path(DEFAULT_INPUT)
        outdir = Path(DEFAULT_OUTDIR)
    else:
        ap = argparse.ArgumentParser(description="Plot sentiment summaries from CSV")
        ap.add_argument("--input", default=DEFAULT_INPUT, help="Input sentiment CSV")
        ap.add_argument("--outdir", default=DEFAULT_OUTDIR, help="Directory to save plots")
        args = ap.parse_args()
        in_path = Path(args.input)
        outdir = Path(args.outdir)

    if not in_path.exists():
        print(f"Input CSV not found: {in_path.resolve()}")
        return

    df = load_df(in_path)
    if df.empty:
        print("No data to plot.")
        return

    plot_percentages(df, outdir)
    plot_votes_by_sentiment(df, outdir)
    plot_combined(df, outdir)
    plot_trend_by_year(df, outdir)

    print("Plots saved to:")
    for fname in [
        "sentiment_percentages_bar.png",
        "sentiment_percentages_pie.png",
        "upvotes_downvotes_by_sentiment.png",
        "sentiment_combined.png",
        "sentiment_trend_by_year.png",
    ]:
        print(f"  {outdir / fname}")


if __name__ == "__main__":
    main()
